CREATE  TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
  login VARCHAR(256) NOT NULL ,
  full_name VARCHAR(2048) NOT NULL,
  deleted_at DATE NULL ,
  password VARCHAR(256) NOT NULL ,
  constraint pk_users PRIMARY KEY (id) );
